fix(tests): remove @node/types (#386)
stampy.ts tests were failing (e.g. https://github.com/StampyAI/stampy-ui/actions/runs/7854687158/job/21435971107) with the following error:

```
    app/server-utils/stampy.ts:196:45 - error TS2576: Property 'json' does not exist on type 'Response'. Did you mean to access the static member 'Response.json' instead?

    196     json = await (await fetch(url, params)).json()
```

Removed @nodes/types as I think it was due to the types conflict described https://github.com/cloudflare/workerd/issues/1298.